sudo: false

language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - bin

before_script:
  - rm composer.lock
  - composer self-update
  - composer install

script:
  - bin/phpcs
  - bin/phpmd src/ text cleancode,controversial,design,naming,codesize
  - bin/phpspec run --config phpspec.travis.yml

after_script:
  - bin/coveralls -v
